### ISSUE TITLE
Accept 16bit data

### ISSUE THREAD

**Issue by GrubbyHalo** [sagi-z/BackgroundSubtractorCNT#13]
I have modified the CNT subtractor to accept images with 16 bit channels. I think the only values that need tweaking are the threshold and threshold history. i am currently taking the values for those two and scaling them up (Multiplying them by 256). It seems to work but not as good as the original code base. Do you have any suggestions ?

**Comment by sagi-z** [comment]
My suggestion is to convert your 16 bit to 8 bit before using the subtractor. You can parallel this with some kind of multithreaded pipeline (or any other way you see fit).

**Comment by GrubbyHalo** [comment]
I was hoping not to do too many image conversions as i have this running on a raspberry pi but ok, if i can't get the level of quality from the 16bit version i will resort to converting it to an 8 bit image
