### ISSUE TITLE
How to use these package in Android studio?

### ISSUE THREAD

**Issue by Hameednsn** [sagi-z/BackgroundSubtractorCNT#14]
Also, If you can help me how to import these package in Android studio that will be great, I want to build an small android app using foreground and background segmentation. Thank you

**Comment by sagi-z** [comment]
This library is part of OpenCV for some time now. Look for any recent tutorial on how to use OpenCV on android.

**Comment by Hameednsn** [comment]
Thanks for quick response, really appreciate. Let me check on above.
