### ISSUE TITLE
How BackgroundSubtractorCNT Algorithm?

### ISSUE THREAD

**Issue by kakeru-516** [sagi-z/BackgroundSubtractorCNT#16]
I was currently experimenting with several algorithms for background diffs and your algorithm showed very lightweight behavior. I am very impressed, and would like to thank you for your help. However, I am not sure how this wonderful algorithm of yours works, so I would like to know an explanation with formulas, etc. Please forgive me for borrowing this place to ask you this question.

**Comment by sagi-z** [comment]
Hi, I'm happy that you find this interesting. At the moment the documentation for the algorithm is not formulated in a way it can be mathematically compared to others. It is however explained in https://sagi-z.github.io/BackgroundSubtractorCNT/doxygen/html/index.html
