### ISSUE TITLE
Question >>  Is this algorithm implementable in hsls shader language?

### ISSUE THREAD

**Issue by sperglord8008s** [sagi-z/BackgroundSubtractorCNT#17]
Hi sagi-z . Just a quick question as title , basically looking for a an easy shader implementation for MPC-HC or the like.

 Otherwise really impressive work here , thanks for your opensourcery effort :) 
 
 cheers

**Comment by sagi-z** [comment]
Hi, the algorithm is pretty simple, if u have the time I think it's portable to anything. It simply based on tracking changes in a pixel color values with a treshold, if not changed for a certain period then it's a background. It's so lightweight it runs of the cpu now.

Good luck with that and thanks.
Cheers.
