### ISSUE TITLE
Does this bgs algorithm have better performance than MOG2?

### ISSUE THREAD

**Issue by lzhaozi** [sagi-z/BackgroundSubtractorCNT#9]
I have 2 questions to ask.
1. I've seen that this algorithm has similar speed performance as MOG2 on high end CPU, I want to know if it have better or much better accuracy than MOG2?
2. We know that MOG2 can not only detect the moving foreground people, but also can detect their shadows and the shadows can be easily erased by setting threshold higher than 127 in program. What I want to ask is, can CNT be robust to the shadows as MOG2? Because the shadows is in fact false detections for us, from the user's view.
I am currently using MOG2, and planing to switch to CNT. Does anybody have used it and can answer my question?

**Comment by sagi-z** [comment]
1. From visually testing it against several use cases it seemed to be equal in quality, maybe a little less sensitive to environmental light changes.
2. There is currently no shadow support and I'm currently too occupied elsewhere to do any work on this.
